### ISSUE TITLE
Not yet published?

### ISSUE THREAD

**Issue by pascalduez** [jonathantneal/postcss-preset-env#1]
Hi,
I'm really impatient to start using this preset, but discovered it's not yet pulished.
Is it intentional?

I'm gonna test it by cloning in the meantime ;)

**Comment by pascalduez** [comment]
```
ModuleBuildError: Module build failed: BrowserslistError: Unknown version 59 of firefox
```

**Comment by jonathantneal** [comment]
hey @pascalduez, it looks like you didn’t pass your plugin options into the `feature` key. See https://github.com/jonathantneal/postcss-preset-env#features

You have:

```js
  require('postcss-preset-env')(Object.assign({
    'css-variables': {
      variables: theme,
      preserve: true,
    },
    config,
  }));
```

And you need to have:

```js
  require('postcss-preset-env')(Object.assign({
    features: {
      'css-variables': {
        variables: theme,
        preserve: true,
      },
      config,
    },
  }));
```

**Comment by jonathantneal** [comment]
As for why this is not published, it’s because I want to give it some time to get tested, like you are doing!

**Comment by JLHwung** [comment]
Oops, I thought the package is unpublished to npm for some technical reason until I see this post. I published to npm and would like to transfer the ownership to you @jonathantneal.

**Comment by jonathantneal** [comment]
@JLHwung, yes, would you please transfer the repository to me? My npm name is **jonathantneal** (https://www.npmjs.com/~jonathantneal).

I’m now waiting on the color module to be spec-compliant. All this means is that v2.0.0 will be extremely breaking.

**Comment by JLHwung** [comment]
Hi @jonathantneal,
I have transferred the ownership to you, could you find any notifications?
Now I can't edit any collaborators so I guess I have transferred. Any suggestions is welcome.
