### ISSUE TITLE
Add break properties fallback

### ISSUE THREAD

**Issue by shrpne** [jonathantneal/postcss-preset-env#11]
`break-inside`, `break-before`, `break-after` properties should fallback to `page-break-` alias.

This fallback has removed from autoprefixer https://github.com/postcss/autoprefixer/issues/972
I made [`postcss-page-break`](https://github.com/shrpne/postcss-page-break) plugin for this and want to add it to `postcss-preset-env`. But first, `break-` feature should be added to [`css-db`](https://github.com/jonathantneal/css-db).

**Comment by jonathantneal** [comment]
Yes, this is exactly where this plugin belongs. First, you’ve done such a great job here. I am so impressed that you not only added the PR here but also to cssdb. You’ve made me very happy. Let me review this. I have one concern with the order of the output (the fallback properties appearing after the future property).

**Comment by shrpne** [comment]
> the fallback properties appearing after the future property
It is mistake in the readme, the actual order in the output code is correct. I will fix readme soon.

**Comment by jonathantneal** [comment]
Added via https://github.com/jonathantneal/postcss-preset-env/commit/96225f7840baf35f9f18b47b40b4481b97e462fb

PR made to update your README https://github.com/shrpne/postcss-page-break/pull/1
