### ISSUE TITLE
Automatically import vars without `importFrom`

### ISSUE THREAD

**Issue by nikoloza** [jonathantneal/postcss-preset-env#145]
It there any way to automatically detect variables in all css files without listing files inside `importFrom`?

**Comment by jonathantneal** [comment]
That sounds like a nice feature. Perhaps accomplished through support for glob patterns.

That sounds like a nice feature for https://github.com/csstools/postcss-custom-utils

That is the library which will be handling imports for PostCSS Preset Env, PostCSS Custom Properties, PostCSS Custom Media, PostCSS Custom Selectors, and PostCSS Custom Env.

**Comment by minimit** [comment]
Yes it would be a nice feature, postcss-custom-properties already does it!
@jonathantneal you should know how since you have that repository too :)

**Comment by minimit** [comment]
I don't know why but now it works to me, exportTo without importFrom:

```
const path = require('path')
const fs = require('fs')

module.exports = {
  parser: 'postcss-scss',
  map: true,
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {
      stage: 0,
      exportTo: 'dist/test.js',
      features: {
        'color-mod-function': { unresolved: 'warn' }
      }
    },
    'postcss-mixins': {},
    'postcss-nesting': {},
    'postcss-simple-vars': {},
    'postcss-extend-rule': {},
    'postcss-object-fit-images': {},
    autoprefixer: {}
  }
}

```

Fresh npm install also.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
