### ISSUE TITLE
Doesn't expand css :matches()

### ISSUE THREAD

**Issue by eablokker** [jonathantneal/postcss-preset-env#17]
:matches() is a stage 3 feature.

It looks like this:
```
p:matches(:first-child, .special) {
  color: red;
}
```

When I run it through postcss-preset-env I don't see any changes. I tried it with `>0.001%` browserslist and various stages.

There is a PostCSS Plugin that does this, so it's not difficult: [postcss-selector-matches](https://github.com/postcss/postcss-selector-matches).

It transforms the above into this:
```
p:first-child, p.special {
  color: red;
}
```

Is postcsss-preset-env supposed to do this? Or was this just an oversight?

**Comment by jonathantneal** [comment]
Released in v3.5.0. Thank you again, @eablokker !
