### ISSUE TITLE
Hardcoded github repo is causing package to install with no bundle

### ISSUE THREAD

**Issue by jkantr** [jonathantneal/postcss-preset-env#6]
`"postcss-font-family-system-ui": "github:jonathantneal/postcss-font-family-system-ui",` in the `package.json` is causing the github version of your package to be pulled in... which doesn't run the build / contain a distributable bundle.. so `import` is left in the package. Clearly this breaks `precss` (since it depends on this package).

Please just have this package depend on a non-namespaced `postcss-font-family-system-ui`, since it's at the same HEAD as the repo version anyway, and someone else can be fixed the headache of trying to figure out what the heck is going on when they want to compiled their bootstrap 4 scss...

Edit: better yet, just merge #3

**Comment by jonathantneal** [comment]
This was resolved by https://github.com/jonathantneal/postcss-preset-env/pull/5
